### ISSUE TITLE
To add "Spiral matrix "problem

### ISSUE THREAD

**Issue by Amit-yadav099** [KamandPrompt/HackQuest#18]
hello @KamandPrompt
i am newbie and want to contribute in your intermediate problem section by adding the code of  "Spiral matrix" problem
kindly assign this task to me under the Hacktoberfest2024

problem statement:
ou are given two integers m and n, which represent the dimensions of a matrix.

You are also given the head of a linked list of integers.

Generate an m x n matrix that contains the integers in the linked list presented in spiral order (clockwise), starting from the top-left of the matrix. If there are remaining empty spaces, fill them with -1.

Return the generated matrix.

Input: m = 3, n = 5, head = [3,0,2,6,8,1,7,9,4,2,5,5,0]

![image](https://github.com/user-attachments/assets/883d74c8-6310-4d22-a521-bbacf96dce26)
Explanation: The diagram above shows how the values are printed in the matrix.
Note that the remaining spaces in the matrix are filled with -1.

Output: [[3,0,2,6,8],[5,0,-1,-1,1],[5,2,4,9,7]]

**Comment by Stormbreakerr20** [comment]
There is no need of creating a new issue for this, you can direclty contribute this problem to one of the folder based on the difficulty of this problem. Please follow the [Contribution Guidelines](https://github.com/KamandPrompt/HackQuest?tab=readme-ov-file#contribution-guidelines-) while contributing.
